{ self, ... }:
{
  imports = [
    self.homeModules.audacious
    self.homeModules.bat
    self.homeModules.btop
    self.homeModules.browser
    self.homeModules.cava
    self.homeModules.codex
    self.homeModules.colors
    self.homeModules.editor
    self.homeModules.fzf
    self.homeModules.fish
    self.homeModules.git
    self.homeModules.fastfetch
    self.homeModules.gaming
    self.homeModules.gnome
    self.homeModules.ghostty
    self.homeModules.gtk
    self.homeModules.kitty
    self.homeModules.micro
    self.homeModules.nemo
    self.homeModules.niri
    self.homeModules.obsidian
    self.homeModules.packages
    self.homeModules.retroarch
    self.homeModules.rofi
    self.homeModules.scripts
    self.homeModules.starship
    self.homeModules.swayosd
    self.homeModules.swaync
    self.homeModules.waypaper
    self.homeModules.waybar
    self.homeModules.yazi
    self.homeModules.zellij
    self.homeModules.zoxide
    self.homeModules.xdg-mimes
  ];
}
