# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:base00)\
$username\
$hostname\
[](fg:base00 bg:base01)\
$directory\
[](fg:base01 bg:base02)\
$git_branch\
$git_state\
[](fg:base02 bg:base03)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$ruby\
$custom\
[](fg:base03 bg:base04)\
$docker_context\
$nix_shell\
[](fg:base04)\
$character(bg:base04)\
"""

right_format = "$git_status"

# add_newline = true
command_timeout = 1000
scan_timeout = 300
palette         = "base16_nord_night"

[character]
format                    = "[$symbol ]($style bold)"
success_symbol            = "[  ](fg:base14)" #A3BE8C
error_symbol              = "[  ](fg:base11)" #BF616A
vimcmd_replace_one_symbol = "[  ](fg:base14)" #A3BE8C
vimcmd_replace_symbol     = "[  ](fg:base13)" #EBCB8B
vimcmd_symbol             = "[  ](fg:base13)" #EBCB8B
vimcmd_visual_symbol      = "[  ](fg:base07)" #8FBCBB

[username]
disabled = false
style_root = "bold fg:base11 bg:base00" #BF616A
style_user = "bold fg:base15 bg:base00" #B48EAD
format = "[ $user]($style)"

[hostname]
disabled = false
ssh_symbol = "🌐"
format = "[$ssh_symbol$hostname ]($style)"
style = "fg:base15 bg:base00" #B48EAD

[directory]
disabled = false
format            = "[ $path ]($style)"
style             = "fg:base14 bg:base01" #A3BE8C
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "
"Projects"  = " "
"Workspace" = "󰲋 "

[git_branch]
disabled = false
format = '[[ $symbol $branch ]($style)]($style)'
style  = "fg:base12 bg:base02" # #D08770 #3B4252
symbol = ""

[git_state]
disabled = false
style = "fg:base12 bg:base02"

[git_status]
disabled = false
format = '[ $all_status$ahead_behind ]($style)'
conflicted = "[=$count](fg:base11)"
ahead = "[⇡$count](fg:base14)"
behind = "[⇣$count](fg:base13)"
diverged = "[⇕ $ahead_count/$behind_count](fg:base11)"
untracked = "[?$count](fg:base10)"
modified = "[!$count](fg:base15)"
staged = "[+$count](fg:base14)"
stashed = "[\\$$count](fg:base12)"
renamed = "[»$count](fg:base13)"
deleted = "[✘$count](fg:base11)"
style  = "fg:base04" # #D08770 #3B4252

[c]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base02)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[docker_context]
disabled = false
format          = '[[ $symbol $context ](fg:base05 bg:base03)]($style)$path' # #E5E9F0 #4C566A
only_with_files = false
style           = "fg:base01 bg:base04" # #E5E9F0 #4C566A
symbol          = " "

[elixir]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base02)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[elm]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base02)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[nix_shell]
disabled = false
format = '[$symbol $name ]($style)'
style  = "fg:base01 bg:base04" # #E5E9F0 #434C5E
symbol = ""

[golang]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[haskell]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[java]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[julia]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[nodejs]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[rust]
disabled = false
format = '[[ $symbol ($version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[ruby]
disabled = false
format = '[[ $symbol( $version) ](fg:base07 bg:base03)]($style)' # #8FBCBB #434C5E
style  = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol = " "

[custom.nix]
disabled = false
command           = "nix --version | cut -d' ' -f3" 
description       = "nix language version"
detect_extensions = ["nix"]
format            = '[ $symbol( $output) ]($style)' # #8FBCBB #434C5E
style             = "fg:base07 bg:base03" # #8FBCBB #434C5E
symbol            = "󱄅 "

[time]
disabled    = false
format      = '[ $time](fg:base04)' # #A3BE8C
time_format = '%T'

# For some reason starship does not support base 16 numbers in identifiers,
# i.e. a name like "base0A" won't work. Use base 10 instead.
[palettes.base16_nord]
# Polar Night (backgrounds) 
base00 = "#2E3440"
base01 = "#3B4252"
base02 = "#434C5E"
base03 = "#4C566A"

# Snow Storm (foregrounds)
base04 = "#D8DEE9"
base05 = "#E5E9F0"
base06 = "#ECEFF4"

# Frost (cold accents)
base07 = "#8FBCBB"
base08 = "#88C0D0"
base09 = "#81A1C1"
base10 = "#5E81AC"

# Aurora (accents)
base11 = "#BF616A"
base12 = "#D08770"
base13 = "#EBCB8B"
base14 = "#A3BE8C"
base15 = "#B48EAD"

[palettes.base16_nord_night]
# Polar Night (backgrounds) 
base00 = "#252933" # override
base01 = "#3B4252"
base02 = "#434C5E"
base03 = "#4C566A"

# Snow Storm (foregrounds)
base04 = "#C0C5CF" # override
base05 = "#E5E9F0"
base06 = "#ECEFF4"

# Frost (cold accents)
base07 = "#8FBCBB"
base08 = "#88C0D0"
base09 = "#81A1C1"
base10 = "#5E81AC"

# Aurora (accents)
base11 = "#BF616A"
base12 = "#D08770"
base13 = "#EBCB8B"
base14 = "#A3BE8C"
base15 = "#B48EAD"
# Note the use of Catppuccin color 'peach'
